# Generated by Django 3.2 on 2021-05-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=27)),
                ('password', models.CharField(max_length=200)),
                ('profilephoto', models.ImageField(default='default.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('addr', models.TextField()),
                ('phno', models.IntegerField()),
                ('oxygenpricepercontainer', models.FloatField()),
                ('foreign_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.sellers')),
            ],
        ),
    ]
