# Generated by Django 3.2 on 2021-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='oxygenpricepercontainer',
            new_name='oxyprice',
        ),
    ]
