# Generated by Django 3.2 on 2021-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_sellers_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='profilephoto',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
