# Generated by Django 3.2 on 2021-05-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210519_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('phno', models.IntegerField()),
                ('oxygenpricepercontainer', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=27)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='place',
            name='foreign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.sellers', unique=True),
        ),
    ]
