# Generated by Django 3.2 on 2021-05-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210523_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='foreign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.sellers'),
        ),
    ]
