# Generated by Django 3.2 on 2021-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_sellers_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='profilephoto',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
