# Generated by Django 3.2 on 2021-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_foreign_id_places_foreign_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='oxygenpricepercontainer',
            new_name='oxyprice',
        ),
        migrations.AddField(
            model_name='places',
            name='addr',
            field=models.TextField(default=''),
        ),
    ]
